development:
  adapter: postgresql
  database: mobile_home_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: mobile_home_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: mobile_home_production
  pool: 5
  timeout: 5000
